### ISSUE TITLE
com.sap.refapps:build-tools:jar:1.0 not found

### ISSUE THREAD

**Issue by nstumpe** [SAP-samples/cloud-cf-espm#1]
Hello,

I followed the instruction. When I execute "mvn clean install" in the java folder, I get:

Plugin org.apache.maven.plugins:maven-pmd-plugin:3.7 or one of its dependencies could not be resolved: Failure to find com.sap.refapps:build-tools:jar:1.0

/regards

**Comment by navinkrishnan** [comment]
Hi @rstumpe 

Thanks for pointing out.

Looks like the module build-tools is not built and the jar is not available.

Can you please run "mvn clean install" command from the root folder instead of java folder?

I will update the readme as well.

**Comment by nstumpe** [comment]
Thanks, seems to work.

In the meanwhile, I did run "mvn clean install"  in the "build-tools" folder, which installs the build-tools in my local maven repository, too.

But seems that the correct location is to run  "mvn clean install" it in the root folder.
