### ISSUE TITLE
cf cs xsuaa default espm-uaa -c xs-security.json fails

### ISSUE THREAD

**Issue by nstumpe** [SAP-samples/cloud-cf-espm#2]
Step 2 - create postgree service:
cf cs xsuaa default espm-uaa -c xs-security.json results in: The plan default could not be found for service xsuaa
cf cs xsuaa application espm-uaa -c xs-security.json works

Note: manifest.yml defines "espm-uaa-refapps" -> so you have to chenge either manifest.yml or 
cf cs xsuaa application espm-uaa-refapps -c xs-security.json works must be called here!

**Comment by navinkrishnan** [comment]
Noted. Thanks
