### ISSUE TITLE
Failure to find com.sap.db.jdbc:ngdbc:jar:2.0.13

### ISSUE THREAD

**Issue by nstumpe** [SAP-samples/cloud-cf-espm#3]
Step 4 - Build the application "Note: When running the application in internet..."

executing mvn install:install-file -Dfile=<path-to-file> -DgroupId=com.sap.db -DartifactId=ngdbc -Dversion=2.0.13 -
Dpackaging=jar

Installing the driver this way will result in an error when the application is compiled afterwards:
Failure to find com.sap.db.jdbc:ngdbc:jar:2.0.13

The application code includes com.sap.db.jdbc !

executing mvn install:install-file -Dfile=<path-to-file> -DgroupId=com.sap.db.jdbc -DartifactId=ngdbc -Dversion=2.0.13 -
Dpackaging=jar

works.

**Comment by navinkrishnan** [comment]
Noted and updated. Thanks for your input.
