### ISSUE TITLE
Securing the Backend Applicatio Build error - com.sap.xs2.security

### ISSUE THREAD

**Issue by nstumpe** [SAP-samples/cloud-cf-espm#5]
Securing the Backend Application

I uncommented the lines in step 1 and step 2.
I run "mvn clean install" in the root folder:

"Failure to find com.sap.xs2.security:java-container-security:jar:0.24.3"

**Comment by navinkrishnan** [comment]
com.sap.xs2.security:java-container-security has been removed.

We need to use com.sap.cloud.security.xsuaa instead.

You can refer the security implementation logic here [SAP/cloud-espm-multi-environment](https://github.com/SAP/cloud-espm-multi-environment)

i will update the code shortly. Thank you.

**Comment by nstumpe** [comment]
I included:

	<dependency>
			<groupId>com.sap.cloud.security.xsuaa</groupId>
			<artifactId>api</artifactId>
			<version>1.1.0</version>
			<scope>provided</scope>
		</dependency>

the code compiles now. But #4 still remains. The application does not start.

**Comment by navinkrishnan** [comment]
Implementation Changed.

Security is now enabled by default and no code change required. Please take a fresh checkout.
