### ISSUE TITLE
No Products available

### ISSUE THREAD

**Issue by nstumpe** [SAP-samples/cloud-cf-espm#6]
I followed the Readme. The application is built correctly and running after having everything deployed via: cf push -f manifest.yml

I also set all role-configurations as mentioned in the readme.

I access the UI via:
<myTrialAccount>->trial->refapps-espm-ui-> then I follow the generated link

I get the UI5 UI but I dont see no data: "No products available"

Note:
When I connect to the database directly using an ssh tunnel and postgresql-client
(found the manual here: https://help.sap.com/viewer/6be7ed96ddeb4e158c2107c434142545/Cloud/en-US/7547876937594510aa13cfaf693d07b1.html)

I see that tables and data is there. So basically the setup of the database and the binding to the java backend sould be ok....

**Comment by mahaluckshmi** [comment]
Hi,

Can you please check if your manifest is proper. DATABASE_TYPE: "postgresql", destination url, etc.
